# Generated by Django 5.2.7 on 2025-12-25 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11, 'کمتر از  11 رقم وارد نکنید .'), django.core.validators.MaxLengthValidator('11,بیشتر از 11 رقم وارد نکنید ')])),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'سفارش باید بیش از یک عدد باشه'), django.core.validators.MaxValueValidator(10, 'سفارش باید کمتر  از 11 عدد باشه ')])),
            ],
        ),
        migrations.CreateModel(
            name='SuggestionsCritics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=11, validators=[django.core.validators.MinLengthValidator(11, 'کمتر از 11 رقم وارد نکنید.'), django.core.validators.MaxLengthValidator(11, 'بیشتر از 11 رقم وارد نکنید')])),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ingredients', models.CharField(blank=True, max_length=255)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('old_price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('price', models.PositiveBigIntegerField()),
                ('image', models.ImageField(upload_to='foods/')),
                ('food_types', models.ManyToManyField(to='app.foodtype')),
            ],
        ),
    ]
